# ======================================================================
# WCP 360 – golangci-lint configuration
# Creator: HADJ RAMDANE Yacine | V0.1.0
# ======================================================================

version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - gocritic
    - gofmt
    - misspell
    - noctx
    - sqlcloserows
    - unparam

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: "_test.go"
      linters: [gocritic]
    - path: "internal/models/"
      linters: [unused]
