#!/usr/bin/env bash
# ======================================================================
# WCP 360 – Modern Web Control Panel (Go + Caddy + FrankenPHP)
# ======================================================================
# Creator: HADJ RAMDANE Yacine | V0.0.5
# File: scripts/install.sh
# Description: Interactive installer — creates FHS dirs, systemd unit,
#              generates JWT secret, hashes admin password.
#              Usage: sudo bash install.sh [--non-interactive]
# ======================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[WCP360]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; }

BINARY_PATH="${BINARY_PATH:-/opt/wcp360/bin/wcp360}"
CONFIG_PATH="/etc/wcp360/wcp360.yaml"
NON_INTERACTIVE=false
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=true

check_root() {
    [[ $EUID -eq 0 ]] || { error "Run as root: sudo bash install.sh"; exit 1; }
}

create_directories() {
    info "Creating FHS directories..."
    local dirs=("/opt/wcp360/bin" "/etc/wcp360" "/etc/wcp360/tls"
                 "/var/lib/wcp360" "/var/log/wcp360" "/srv/www")
    for d in "${dirs[@]}"; do
        mkdir -p "$d"
        success "$d"
    done
}

create_system_user() {
    id -u wcp360 &>/dev/null && { success "wcp360 user already exists"; return; }
    useradd --system --no-create-home --shell /sbin/nologin --home-dir /opt/wcp360 wcp360
    success "wcp360 system user created"
}

generate_jwt_secret() {
    if command -v openssl &>/dev/null; then
        openssl rand -hex 32
    else
        tr -dc 'a-f0-9' < /dev/urandom | head -c 64
    fi
}

hash_password() {
    local password="$1"
    if command -v htpasswd &>/dev/null; then
        htpasswd -nbB -C 12 admin "$password" | cut -d: -f2
    elif command -v python3 &>/dev/null; then
        python3 -c "import bcrypt; print(bcrypt.hashpw(b'${password}', bcrypt.gensalt(12)).decode())"
    else
        error "Cannot hash password: install apache2-utils (htpasswd) or python3-bcrypt"
        exit 1
    fi
}

get_admin_credentials() {
    if $NON_INTERACTIVE; then
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -hex 12)}"
        warn "Non-interactive: admin=${ADMIN_USERNAME}, password=${ADMIN_PASSWORD}"
    else
        read -rp "Admin username [admin]: " ADMIN_USERNAME
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        read -rsp "Admin password: " ADMIN_PASSWORD; echo
        [[ -n "$ADMIN_PASSWORD" ]] || { error "Password cannot be empty"; exit 1; }
    fi
    info "Hashing admin password (bcrypt cost=12)..."
    ADMIN_HASH=$(hash_password "$ADMIN_PASSWORD")
    success "Password hashed"
}

write_config() {
    local jwt_secret listen_addr data_dir
    jwt_secret=$(generate_jwt_secret)
    listen_addr="${LISTEN_ADDR:-:8080}"
    data_dir="${DATA_DIR:-/srv/www}"

    cat > "$CONFIG_PATH" << EOF
# WCP360 Configuration — generated by install.sh
# Edit: /etc/wcp360/wcp360.yaml

listen_addr: "$listen_addr"
env: "production"
log_level: "info"
database_path: "/var/lib/wcp360/state.db"
data_dir: "$data_dir"
jwt_secret: "$jwt_secret"
admin_username: "$ADMIN_USERNAME"
admin_password_hash: "$ADMIN_HASH"
EOF
    chmod 600 "$CONFIG_PATH"
    success "Config written to $CONFIG_PATH"
}

set_permissions() {
    chown -R wcp360:wcp360 /opt/wcp360 /var/lib/wcp360 /var/log/wcp360
    chown root:wcp360 /etc/wcp360
    chmod 750 /etc/wcp360
    [[ -f "$BINARY_PATH" ]] && chmod 755 "$BINARY_PATH"
    success "Permissions set"
}

install_systemd() {
    cat > /etc/systemd/system/wcp360.service << EOF
[Unit]
Description=WCP360 Web Control Panel
After=network.target
Requires=network.target

[Service]
Type=simple
User=wcp360
Group=wcp360
ExecStart=$BINARY_PATH
Restart=always
RestartSec=5
WorkingDirectory=/opt/wcp360

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/wcp360 /var/log/wcp360 /srv/www
PrivateTmp=true
PrivateDevices=true
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    success "Systemd unit installed: wcp360.service"
}

main() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════╗${NC}"
    echo -e "${BLUE}║  WCP360 Installer v0.0.5         ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════╝${NC}"
    echo ""
    check_root
    create_directories
    create_system_user
    get_admin_credentials
    write_config
    set_permissions
    install_systemd
    echo ""
    success "Installation complete!"
    info "Start: systemctl enable --now wcp360"
    info "Admin: http://YOUR_SERVER_IP:8080/admin/login"
    echo ""
}

main "$@"
